name: json_to_dart_web
description: Convert json to dart class

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_to_dart:
    path: ./json_to_dart
  
dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0